version: '3.7'

services:
  api:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./server/.env.dev
    depends_on:
      - properties-db
  scraper:
    build: ./scraper
    command: python app.py
    volumes:
      - ./scraper/:/usr/src/app/
    env_file:
      - ./scraper/.env.dev
    depends_on:
      - properties-db
  properties-db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=properties
      - POSTGRES_PASSWORD=properties
      - POSTGRES_DB=properties_dev
volumes:
  postgres_data: